page_industriesUI <- function(...) {
  djpr_tab_panel(
    title = "Industries",
    h1("Victoria's industries"),
    br(),
    "On this page, we explore the economic and financial performance of Victorian industries. ",
    "The ",
    shiny::a("ABS", href = "https://www.abs.gov.au/ausstats/abs@.nsf/mf/1292.0"),
    " classifies businesses into one of 19 broad industry divisions, each of which is further ",
    " divided into sub-divisions, groups, and classes.",
    br(),
    br(),
    "Note that industries data is not seasonally adjusted and is released quarterly.",
    br(),
    h4("Number of people employed by industry"),
    uiOutput("table_industries_summary"),
    djpr_plot_ui("industries_empchange_sincecovid_bar"),
    br(),
    focus_box(
      selectInput(
        "chosen_industry",
        label = "Choose an industry",
        choices = c(
          "Accommodation and Food Services",
          "Arts and Recreation Services",
          "Education and Training",
          "Transport, Postal and Warehousing",
          "Financial and Insurance Services",
          "Electricity, Gas, Water and Waste Services",
          "Professional, Scientific and Technical Services",
          "Health Care and Social Assistance",
          "Agriculture, Forestry and Fishing",
          "Mining",
          "Manufacturing",
          "Information Media and Telecommunications",
          "Administrative and Support Services",
          "Public Administration and Safety",
          "Construction",
          "Wholesale Trade",
          "Retail Trade",
          "Rental, Hiring and Real Estate Services",
          "Other Services"
        ),
        width = "100%"
      ),
      column(
        6,
        djpr_plot_ui("industries_emp_line")
      ),
      column(
        6,
        uiOutput("industries_employment")
      ),
      br(),
      djpr_plot_ui("industries_emp_bysex_bar")
    ),
    br(),
    htmlOutput("industries_footnote"),
    br()
  )
}

page_industries <- function(input, output, session, plt_change) {

  output$table_industries_summary <- renderUI({
    table_industries_summary() %>%
      flextable::htmltools_value()
  })

  djpr_plot_server("industries_empchange_sincecovid_bar",
                   plot_function = viz_industries_empchange_sincecovid_bar,
                   data = filter_dash_data(c(
                     "A84601680F",
                     "A84601683L",
                     "A84601686V",
                     "A84601665J",
                     "A84601704L",
                     "A84601707V",
                     "A84601710J",
                     "A84601638A",
                     "A84601653X",
                     "A84601689A",
                     "A84601656F",
                     "A84601713R",
                     "A84601668R",
                     "A84601695W",
                     "A84601698C",
                     "A84601650T",
                     "A84601671C",
                     "A84601641R",
                     "A84601716W",
                     "A84601662A"
                   ),
                   df = dash_data
                   ),
                   plt_change = plt_change,
                   date_slider = FALSE
  )

  djpr_plot_server("industries_emp_line",
                   plot_function = viz_industries_emp_line,
                   data = filter_dash_data(c(
                     "A84601680F",
                     "A84601683L",
                     "A84601686V",
                     "A84601665J",
                     "A84601704L",
                     "A84601707V",
                     "A84601710J",
                     "A84601638A",
                     "A84601653X",
                     "A84601689A",
                     "A84601656F",
                     "A84601713R",
                     "A84601668R",
                     "A84601695W",
                     "A84601698C",
                     "A84601650T",
                     "A84601671C",
                     "A84601641R",
                     "A84601716W",
                     "A84601662A"
                   ),
                   df = dash_data
                   ),
                   chosen_industry = reactive({
                     input$chosen_industry
                   }),
                   plt_change = plt_change,
                   date_slider = TRUE,
                   date_slider_value_min = Sys.Date() - (365 * 10),
                   width_percent = 45,
                   height_percent = 75
  )

  djpr_plot_server("industries_emp_bysex_bar",
                   plot_function = viz_industries_emp_bysex_bar,
                   data = filter_dash_data(c(
                     "females_greater melbourne_accommodation and food services_employed full-time",
                     "females_greater melbourne_administrative and support services_employed full-time",
                     "females_greater melbourne_agriculture, forestry and fishing_employed full-time",
                     "females_greater melbourne_arts and recreation services_employed full-time",
                     "females_greater melbourne_construction_employed full-time",
                     "females_greater melbourne_education and training_employed full-time",
                     "females_greater melbourne_electricity, gas, water and waste services_employed full-time",
                     "females_greater melbourne_financial and insurance services_employed full-time",
                     "females_greater melbourne_health care and social assistance_employed full-time",
                     "females_greater melbourne_information media and telecommunications_employed full-time",
                     "females_greater melbourne_manufacturing_employed full-time",
                     "females_greater melbourne_mining_employed full-time",
                     "females_greater melbourne_other services_employed full-time",
                     "females_greater melbourne_professional, scientific and technical services_employed full-time",
                     "females_greater melbourne_public administration and safety_employed full-time",
                     "females_greater melbourne_rental, hiring and real estate services_employed full-time",
                     "females_greater melbourne_retail trade_employed full-time",
                     "females_greater melbourne_transport, postal and warehousing_employed full-time",
                     "females_greater melbourne_wholesale trade_employed full-time",
                     "males_greater melbourne_accommodation and food services_employed full-time",
                     "males_greater melbourne_administrative and support services_employed full-time",
                     "males_greater melbourne_agriculture, forestry and fishing_employed full-time",
                     "males_greater melbourne_arts and recreation services_employed full-time",
                     "males_greater melbourne_construction_employed full-time",
                     "males_greater melbourne_education and training_employed full-time",
                     "males_greater melbourne_electricity, gas, water and waste services_employed full-time",
                     "males_greater melbourne_financial and insurance services_employed full-time",
                     "males_greater melbourne_health care and social assistance_employed full-time",
                     "males_greater melbourne_information media and telecommunications_employed full-time",
                     "males_greater melbourne_manufacturing_employed full-time",
                     "males_greater melbourne_mining_employed full-time",
                     "males_greater melbourne_other services_employed full-time",
                     "males_greater melbourne_professional, scientific and technical services_employed full-time",
                     "males_greater melbourne_public administration and safety_employed full-time",
                     "males_greater melbourne_rental, hiring and real estate services_employed full-time",
                     "males_greater melbourne_retail trade_employed full-time",
                     "males_greater melbourne_transport, postal and warehousing_employed full-time",
                     "males_greater melbourne_wholesale trade_employed full-time",
                     "females_rest of vic._accommodation and food services_employed full-time",
                     "females_rest of vic._administrative and support services_employed full-time",
                     "females_rest of vic._agriculture, forestry and fishing_employed full-time",
                     "females_rest of vic._arts and recreation services_employed full-time",
                     "females_rest of vic._construction_employed full-time",
                     "females_rest of vic._education and training_employed full-time",
                     "females_rest of vic._electricity, gas, water and waste services_employed full-time",
                     "females_rest of vic._financial and insurance services_employed full-time",
                     "females_rest of vic._health care and social assistance_employed full-time",
                     "females_rest of vic._information media and telecommunications_employed full-time",
                     "females_rest of vic._manufacturing_employed full-time",
                     "females_rest of vic._mining_employed full-time",
                     "females_rest of vic._other services_employed full-time",
                     "females_rest of vic._professional, scientific and technical services_employed full-time",
                     "females_rest of vic._public administration and safety_employed full-time",
                     "females_rest of vic._rental, hiring and real estate services_employed full-time",
                     "females_rest of vic._retail trade_employed full-time",
                     "females_rest of vic._transport, postal and warehousing_employed full-time",
                     "females_rest of vic._wholesale trade_employed full-time",
                     "males_rest of vic._accommodation and food services_employed full-time",
                     "males_rest of vic._administrative and support services_employed full-time",
                     "males_rest of vic._agriculture, forestry and fishing_employed full-time",
                     "males_rest of vic._arts and recreation services_employed full-time",
                     "males_rest of vic._construction_employed full-time",
                     "males_rest of vic._education and training_employed full-time",
                     "males_rest of vic._electricity, gas, water and waste services_employed full-time",
                     "males_rest of vic._financial and insurance services_employed full-time",
                     "males_rest of vic._health care and social assistance_employed full-time",
                     "males_rest of vic._information media and telecommunications_employed full-time",
                     "males_rest of vic._manufacturing_employed full-time",
                     "males_rest of vic._mining_employed full-time",
                     "males_rest of vic._other services_employed full-time",
                     "males_rest of vic._professional, scientific and technical services_employed full-time",
                     "males_rest of vic._public administration and safety_employed full-time",
                     "males_rest of vic._rental, hiring and real estate services_employed full-time",
                     "males_rest of vic._retail trade_employed full-time",
                     "males_rest of vic._transport, postal and warehousing_employed full-time",
                     "males_rest of vic._wholesale trade_employed full-time",
                     "females_greater melbourne_accommodation and food services_employed part-time",
                     "females_greater melbourne_administrative and support services_employed part-time",
                     "females_greater melbourne_agriculture, forestry and fishing_employed part-time",
                     "females_greater melbourne_arts and recreation services_employed part-time",
                     "females_greater melbourne_construction_employed part-time",
                     "females_greater melbourne_education and training_employed part-time",
                     "females_greater melbourne_electricity, gas, water and waste services_employed part-time",
                     "females_greater melbourne_financial and insurance services_employed part-time",
                     "females_greater melbourne_health care and social assistance_employed part-time",
                     "females_greater melbourne_information media and telecommunications_employed part-time",
                     "females_greater melbourne_manufacturing_employed part-time",
                     "females_greater melbourne_mining_employed part-time",
                     "females_greater melbourne_other services_employed part-time",
                     "females_greater melbourne_professional, scientific and technical services_employed part-time",
                     "females_greater melbourne_public administration and safety_employed part-time",
                     "females_greater melbourne_rental, hiring and real estate services_employed part-time",
                     "females_greater melbourne_retail trade_employed part-time",
                     "females_greater melbourne_transport, postal and warehousing_employed part-time",
                     "females_greater melbourne_wholesale trade_employed part-time",
                     "males_greater melbourne_accommodation and food services_employed part-time",
                     "males_greater melbourne_administrative and support services_employed part-time",
                     "males_greater melbourne_agriculture, forestry and fishing_employed part-time",
                     "males_greater melbourne_arts and recreation services_employed part-time",
                     "males_greater melbourne_construction_employed part-time",
                     "males_greater melbourne_education and training_employed part-time",
                     "males_greater melbourne_electricity, gas, water and waste services_employed part-time",
                     "males_greater melbourne_financial and insurance services_employed part-time",
                     "males_greater melbourne_health care and social assistance_employed part-time",
                     "males_greater melbourne_information media and telecommunications_employed part-time",
                     "males_greater melbourne_manufacturing_employed part-time",
                     "males_greater melbourne_mining_employed part-time",
                     "males_greater melbourne_other services_employed part-time",
                     "males_greater melbourne_professional, scientific and technical services_employed part-time",
                     "males_greater melbourne_public administration and safety_employed part-time",
                     "males_greater melbourne_rental, hiring and real estate services_employed part-time",
                     "males_greater melbourne_retail trade_employed part-time",
                     "males_greater melbourne_transport, postal and warehousing_employed part-time",
                     "males_greater melbourne_wholesale trade_employed part-time",
                     "females_rest of vic._accommodation and food services_employed part-time",
                     "females_rest of vic._administrative and support services_employed part-time",
                     "females_rest of vic._agriculture, forestry and fishing_employed part-time",
                     "females_rest of vic._arts and recreation services_employed part-time",
                     "females_rest of vic._construction_employed part-time",
                     "females_rest of vic._education and training_employed part-time",
                     "females_rest of vic._electricity, gas, water and waste services_employed part-time",
                     "females_rest of vic._financial and insurance services_employed part-time",
                     "females_rest of vic._health care and social assistance_employed part-time",
                     "females_rest of vic._information media and telecommunications_employed part-time",
                     "females_rest of vic._manufacturing_employed part-time",
                     "females_rest of vic._mining_employed part-time",
                     "females_rest of vic._other services_employed part-time",
                     "females_rest of vic._professional, scientific and technical services_employed part-time",
                     "females_rest of vic._public administration and safety_employed part-time",
                     "females_rest of vic._rental, hiring and real estate services_employed part-time",
                     "females_rest of vic._retail trade_employed part-time",
                     "females_rest of vic._transport, postal and warehousing_employed part-time",
                     "females_rest of vic._wholesale trade_employed part-time",
                     "males_rest of vic._accommodation and food services_employed part-time",
                     "males_rest of vic._administrative and support services_employed part-time",
                     "males_rest of vic._agriculture, forestry and fishing_employed part-time",
                     "males_rest of vic._arts and recreation services_employed part-time",
                     "males_rest of vic._construction_employed part-time",
                     "males_rest of vic._education and training_employed part-time",
                     "males_rest of vic._electricity, gas, water and waste services_employed part-time",
                     "males_rest of vic._financial and insurance services_employed part-time",
                     "males_rest of vic._health care and social assistance_employed part-time",
                     "males_rest of vic._information media and telecommunications_employed part-time",
                     "males_rest of vic._manufacturing_employed part-time",
                     "males_rest of vic._mining_employed part-time",
                     "males_rest of vic._other services_employed part-time",
                     "males_rest of vic._professional, scientific and technical services_employed part-time",
                     "males_rest of vic._public administration and safety_employed part-time",
                     "males_rest of vic._rental, hiring and real estate services_employed part-time",
                     "males_rest of vic._retail trade_employed part-time",
                     "males_rest of vic._transport, postal and warehousing_employed part-time",
                     "males_rest of vic._wholesale trade_employed part-time"
                   ), df = dash_data) %>%
                     dplyr::group_by(.data$series) %>%
                     dplyr::filter(.data$date == max(.data$date)) %>%
                     dplyr::ungroup(),
                   plt_change = plt_change,
                   chosen_industry = reactive({
                     input$chosen_industry
                   }),
                   date_slider = FALSE,
                   height_percent = 65,
                   width_percent = 100
  )

  output$industries_employment <- renderUI({
    table_industries_employment(chosen_industry = input$chosen_industry) %>%
      flextable::htmltools_value()
  }) %>%
    bindCache(
      series_latestdates,
      input$chosen_industry
    )

  observeEvent(input$link_industries, {
    updateNavbarPage(session, "navbarpage", "tab-industries")
  })

}
