# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

name: styler

jobs:
  run-styler:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: install-packages
        run: |
         Rscript -e "install.packages(c('remotes'), type = 'binary', dependencies = TRUE)"
         Rscript -e "remotes::install_deps(type = 'binary', force = FALSE, dependencies = TRUE)"
      - name: run-styler
        run: |
         Rscript -e "pkgload::load_all()"
         Rscript -e "styler::style_pkg(dry = 'on')"
         Rscript -e "stopifnot(isFALSE(any(style_results$changed)))"
